### ISSUE TITLE
Possible Typos

### ISSUE THREAD

**Issue by Roctober92** [khufkens/snotelr#9]
Hi!

Thanks for the repository. While exploring it a little bit, I came across a few things that I think might be typos. Please look and them and see if they are.

1. download_snotel()

In the documentation for this function, an example given is
`# df = snotel_download(site = snotel_info())`
which _snotel_download_ seems to be a backwards version of the real function. Obviously this isn't a function, and I think the words were just reversed.

2. snotel_phenology()

In the readme, it advertised the function _snow_phenology()_,  which I think you meant to say _snotel_phenology()_

**Comment by khufkens** [comment]
Thanks for spotting this... feel free to correct yourself and ask for a pull request.
Hope the package serves you well.
